### ISSUE TITLE
Test elliptical wing case Master Thesis

### ISSUE THREAD

**Issue by ocayon** [awegroup/Vortex-Step-Method#24]
# Refine Aerodynamic Mesh
- [x] should also write a test for when the #structural panels exceeds the #aerodynamic panels, for both linear and cosine. 
- [x] Added functionality to interpolate geometric input
- [x] Now interpolates both LE and TE
- [x] pytested

Remarks
- User MUST define input from Left-to-Right
- User MUST define aerodynamic input, and thus the sections, perpendicular to the 1/4c line, otherwise accuracy suffers..

# Elliptical wing
- [x] Resolved geometric problem by calculating new sections using the 1/4c line as a starting base. From there using weights and average chords the new LE and TE is calculated, this preserves the original orientation of the sections, within the newly refined sections.
- [x] Converges now, big bug in that one has to remove the wake each time one resets the va
- [x] Can one also update the existing filaments, instead of relying on a function that removes them?
- [x] Double check the AR calculation input
- [x] Get AR = 3 case to converge well
- [x] Check with old thesis script, to see how close you are
- [x] Pytested both the input and output that is `create_geometry_general` and `output_results` functions, so the error MUST be within the `solve_lifting_line_system_matrix_approach_art_visc function` . 

**Next-step**
- [x] Start with pytesting AIC matrix
- [x] Isolate the whole `solve_lifting_line_system_matrix_approach_art_visc function` and write a proper pytest for it 
- [x] Changing reference frame to ENU, was implemented
- [x] Step by step comparison was done with old codd
- [x] the correct difference between AR 3 and AR 20 shows in CL
- [x] CD does not match yet, need to resolve this.
- [x] once matching, write pytest

**Comment by jellepoland** [comment]
There only remains a deviation between gamma_VSM and gamma_VSM_NEW,
This might be due to how gamma is stored inside both "calculate results" functions.
The end result,  cl, cd seem to match very well, so i will leave it as this.
