### ISSUE TITLE
Implementing calculate_results functions

### ISSUE THREAD

**Issue by jellepoland** [awegroup/Vortex-Step-Method#30]
- [x] First step based on the old code has been done, seems to work, some open things remain
- [x] adding some plots
- [x] pytesting this calculate results functions against old code

Thinking through 
- [x] Why the uncorrected alpha is used to calculate L_rel? (was fed through Fmag). Upon comparing to the old code it was found that Fmag needs the uncorrected alpha input and aero_coeffs requires the corrected alpha input.
- [x] Why is a [0,1,0] needed?

**Comment by ocayon** [comment]
1. Reggarding L_rel, in the old code it needs Fmag and aero_coeffs, which is already the corrected alpha in that implementation. It does not deppend on the uncorrected value. 
2. [0,1,0] is needed to know the geometrical span wise direction. It can also be obtained in another way to make it robust against different orientation in the geometry input.
