### ISSUE TITLE
Cl and Cd are inverted in CL-CD plot

### ISSUE THREAD

**Issue by corentintran** [awegroup/Vortex-Step-Method#85]
In the function plot_polars  : src/VSM/plotting.py, lines 801/802
polar_data{1] (Cl) and polar_data[2] (Cd) are inverted in the CL-CD plot,

**Comment by jellepoland** [comment]
Thanks for the issue!

It is resolved, I also added no w CL/CD over alpha.

Updates are live in develop but not yet released on main.
